@startuml action_state_machine

[*] --> ActionStatePending
ActionStatePending --> ActionStateRunning
ActionStateRunning --> ActionStateSucceeded
ActionStateRunning --> ActionStateFailed
ActionStateSucceeded --> [*]
ActionStateFailed --> [*]

ActionStatePending : Action waiting to start
ActionStateSucceeded : All actions completed\nsuccessfully
ActionStateFailed : An action failed

@enduml